import streamlit as st
from chatbot_engine import HybridChatbot

# --- Page Configuration ---
st.set_page_config(
    page_title="Vislona Support Chat",
    page_icon="🤖",
    layout="centered"
)

# --- Vislona Branding ---
st.title("Vislona Customer Support Chatbot 🤖")
st.caption("Your friendly assistant for all Vislona-related queries.")
# 
# --- Chatbot Initialization ---
@st.cache_resource
def load_chatbot():
    """Load the chatbot instance, cached for performance."""
    return HybridChatbot(faq_filepath='data/vislona_faqs.csv')

chatbot = load_chatbot()

# --- Session State Initialization ---
if "messages" not in st.session_state:
    st.session_state.messages = [{"role": "assistant", "content": "Hello! How can I assist you with Vislona today?"}]

# --- Sidebar for Mode Selection ---
st.sidebar.header("Chatbot Settings")
chat_mode = st.sidebar.radio(
    "Choose Chatbot Mode:",
    ('Hybrid', 'FAQ Only', 'Gemini Only'),
    help="""
    - **Hybrid:** Best of both! Fast answers for common questions, smart replies for complex ones.
    - **FAQ Only:** Only answers questions from our knowledge base.
    - **Gemini Only:** All answers are generated by the advanced Gemini model.
    """
)
st.sidebar.markdown("---")
if st.sidebar.button("Clear Chat History"):
    st.session_state.messages = [{"role": "assistant", "content": "Chat history cleared. How can I help you now?"}]
    st.rerun()

# --- Display Chat History ---
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# --- User Input and Chat Logic ---
if prompt := st.chat_input("Ask a question about Vislona..."):
    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Generate and display bot response
    with st.chat_message("assistant"):
        with st.spinner("Vislona is thinking..."):
            response = chatbot.get_response(prompt, mode=chat_mode)
            st.markdown(response)
    
    # Add bot response to chat history
    st.session_state.messages.append({"role": "assistant", "content": response})